### ISSUE TITLE
jsnext:main

### ISSUE THREAD

**Issue by bennybennet** [alax/forward-secrecy#1]
Hi,

could you please consider supporting the "jsnext:main" attribute in your package.json as it would make using this great library easier. For example one could use Rollup to include your Library in node and browser code. 

See: https://github.com/rollup/rollup/wiki/jsnext:main

Thanks, Benny

**Comment by alax** [comment]
Hey Benny, if you want to make a pull request with the changes, I will merge it straightaway. Otherwise, it'll take me a bit to get this handled.

**Comment by bennybennet** [comment]
Hey alax,
ok, will do it, will be my first pull request. ;)

**Comment by bennybennet** [comment]
Would you mind updating your npm package too? :)
